#Ejempl de lista vacia
lista_vacia = []
print ("lista Vacia:, lista_vacia")

#lista de elementos iniciales
lista_elementos = [1, 2, 3, 4, 5]
print("Lista con Elementos Iniciales: ", lista_elementos)

#Ejemplo de Lista de Cadenas
lista_cadenas=["manzana", "banana", "cereza"]
print("Lista de cadenas:", lista_cadenas)

#Ejemplo de Lista de Numeros
lista_numeros = [10, 20, 30, 40.5]
print("Lista de Numeros:", lista_numeros)


#Ejemplo de lista Mixta
lista_mixta = [42, "text", 3.14, [1, 2, 3]]
print("Lista Mixta:", lista_mixta)

#Ejemplo de Lista con Elementos Repetidos
lista_repetidos = [0] * 5
print("Lista con Elementos Repetidos:", lista_repetidos)


#Ejemplo de Lista a partir de otros iterables
cadena= "hola"
lista_de_caracteres = list (cadena)
print("Lista a partir de otros iterables (cadena):", lista_de_caracteres)
