#Ejercicio 10: Buscar y Actualizar la Información en un Diccionario Anidado
# PASO 1. Crea un diccionario que represente una base de datos de empleados de una empresa. El diccionario debe tener:
# nombre_empresa, empleados, que es una lista de diccionarios, donde cada diccionario representa un empleado con:
# id_empleado , nombre, departamento, salario
#PASO2. Escribe una función que busque y actualice el salario de un empleado dado su id_empleado. La función debe:
# Buscar el empleado por su id_empleado.  Actualizar el salario del empleado a un nuevo valor proporcionado.
# Imprimir la información del empleado después de la actualización.