#Ejercicio 5: Diccionario dentro de una Lista
#PASO1. Crea una lista de diccionarios donde cada diccionario representa un producto en una tienda, con claves:
# Nombre, Precio, Cantidad en stock
stock=[
    {
        "nombre": "jabon",
        "precio": 50,
        "cantidad stock" : 6},
     {
        "nombre": "shampoo",
        "precio": 30,
        "cantidad stock": 6
     },
     {
         "nombre" : "servilletas",
         "precio" : 10,
         "cantidad stock" : 8
     }
]
#PASO 2. Imprime el nombre y el precio del segundo producto en la lista.
segundo_producto = stock
print(stock)