#Ejercicio 4: Lista de Diccionarios
#PASO 1. Crea una lista de diccionarios, donde cada diccionario representa un estudiante con las siguientes claves:
# Nombre, Edad, Calificaciones (que es una lista de números)


estudiantes = [ 
  {
                "Nombre": "Juan",
                "Edad" : 18,
                "Calificaciones" : [7, 8, 8, 9]
                }, 
{
                "Nombre" : "Diana",
                "Edad" : 17,
                "Calificaciones" : [8,9,10,10]
                }
]
print(estudiantes)

#PASO 2. Imprime el nombre y las calificaciones del primer estudiante en la lista.
estudiante1=estudiantes

print( "El nombre del primer estudiante es", nombre=estudiantes[])